import type { Metadata } from "next";
import "./globals.css";
// import "@/";

export const metadata: Metadata = {
  title: "OnnxRuntimeWebWasm",
  description: "Generated by mehmetcaloglu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen bg-background font-sans antialiased"}>
        {children}
      </body>
    </html>
  );
}
